version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gotify
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:secret@postgres:5432/gotify?sslmode=disable
      - REDIS_HOST=redis:6379
      - DB_HOST=postgres:5432
      - HTTP_SERVER_ADDRESS=api:3000
      - MAILER_EMAIL_ADDRESS=dudakovict.testing@gmail.com
      - MAILER_EMAIL_PASSWORD=wgzcbapgbylzolbr
    depends_on:
      - postgres
      - redis
    entrypoint: 
      [
        "/app/wait-for.sh", 
        "postgres:5432", 
        "--", 
        "/app/start.sh"
      ]
    command: ["/app/gotify"]
volumes:
  data-volume: