// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dudakovict/gotify/internal/core/verification (interfaces: Storer)

// Package mockvrf is a generated GoMock package.
package mockvrf

import (
	reflect "reflect"

	verification "github.com/dudakovict/gotify/internal/core/verification"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStorer is a mock of Storer interface.
type MockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStorerMockRecorder
}

// MockStorerMockRecorder is the mock recorder for MockStorer.
type MockStorerMockRecorder struct {
	mock *MockStorer
}

// NewMockStorer creates a new mock instance.
func NewMockStorer(ctrl *gomock.Controller) *MockStorer {
	mock := &MockStorer{ctrl: ctrl}
	mock.recorder = &MockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorer) EXPECT() *MockStorerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStorer) Create(arg0 verification.Verificiation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStorerMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStorer)(nil).Create), arg0)
}

// QueryByID mocks base method.
func (m *MockStorer) QueryByID(arg0 uuid.UUID) (verification.Verificiation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryByID", arg0)
	ret0, _ := ret[0].(verification.Verificiation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryByID indicates an expected call of QueryByID.
func (mr *MockStorerMockRecorder) QueryByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryByID", reflect.TypeOf((*MockStorer)(nil).QueryByID), arg0)
}

// Update mocks base method.
func (m *MockStorer) Update(arg0 verification.Verificiation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStorerMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorer)(nil).Update), arg0)
}

// WithinTran mocks base method.
func (m *MockStorer) WithinTran(arg0 func(verification.Storer) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTran", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTran indicates an expected call of WithinTran.
func (mr *MockStorerMockRecorder) WithinTran(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTran", reflect.TypeOf((*MockStorer)(nil).WithinTran), arg0)
}
